name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tag push matching v*, i.e. v1.0.3, v2.0.0

permissions:
  contents: write

jobs:
  release:
    name: Test and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, libxml, mbstring, zip
          coverage: none

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute Tests
        run: vendor/bin/phpunit
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: success()
        with:
          generate_release_notes: true
